apiVersion: "nuclio.io/v1"
kind: "Function"
metadata:
  name: connector
  labels:
    nuclio.io/project-name: "default"
spec:
  httpTimeout: 1000
  handler: "nuclio_handler:handler"
  runtime: "python:3.12"
  build:
    baseImage: "python:3.12"
    commands:
      - "apt-get update -y --fix-missing"
      - "apt-get install -y libgl1-mesa-dev libglib2.0-0"
      - "pip install requests==2.32.5 pydantic-settings==2.13.1 kafka-python==2.3.0 msgpack==1.1.2 opentelemetry-api==1.40.0 opentelemetry-sdk==1.40.0 opentelemetry-exporter-otlp-proto-http==1.40.0"
      - "mkdir -p /home/nuclio/bin/py3.12-whl && pip download msgpack==1.1.2 --only-binary=:all: -d /home/nuclio/bin/py3.12-whl --no-deps"
      - "pip install --upgrade natural-agi-common==0.1.55"
  env:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://mlflow:5000"
  triggers:
    default-http:
      kind: "http"
      attributes:
        port: 5002
