apiVersion: "nuclio.io/v1"
kind: "Function"
metadata:
  name: concept_creator
  labels:
    nuclio.io/project-name: "default"
spec:
  httpTimeout: 1000
  handler: "nuclio_handler:handler"
  runtime: "python:3.9"
  env:
    - name: NEO4J_DSN
      value: "bolt://neo4j:7687"
    - name: NEO4J_USER
      value: "neo4j"
    - name: NEO4J_PASS
      value: "111122223333"
    - name: USE_ENERGY_MINIMIZATION
      value: "false"
  build:
    baseImage: "python:3.9"
    commands:
      - "apt-get update -y --fix-missing"
      - "apt-get install -y libgl1-mesa-dev libglib2.0-0"
      - "pip install numpy requests pydantic-settings neo4j networkx scikit-learn msgpack"
      - "pip install --upgrade natural-agi-common==0.1.45"
  triggers:
    default-http:
      kind: "http"
      attributes:
        port: 5056
