apiVersion: "nuclio.io/v1"
kind: "Function"
metadata:
  name: classification
  labels:
    nuclio.io/project-name: "default"
spec:
  httpTimeout: 1000
  handler: "nuclio_handler:handler"
  runtime: "python:3.9"
  resources:
    limits:
      cpu: "6"
      memory: "8Gi"
    requests:
      cpu: "4"
      memory: "4Gi"
  env:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://jaeger:4317"
    - name: OMP_NUM_THREADS
      value: "1"
    - name: OPENBLAS_NUM_THREADS
      value: "1"
    - name: MKL_NUM_THREADS
      value: "1"
    - name: VECLIB_MAXIMUM_THREADS
      value: "1"
    - name: NUMEXPR_NUM_THREADS
      value: "1"
  build:
    baseImage: "python:3.9"
    commands:
      - "apt-get update -y --fix-missing"
      - "apt-get install -y libgl1-mesa-dev libglib2.0-0"
      - "pip install numpy==1.26.4 requests pydantic-settings neo4j kafka-python networkx scipy msgpack opentelemetry-api opentelemetry-sdk opentelemetry-exporter-otlp-proto-grpc"
      - "pip install --upgrade natural-agi-common==0.1.45"
  triggers:
    default-http:
      kind: "http"
      attributes:
        port: 5001
